name: Validation workflow

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  call-workflow:
    uses: SergeCaron/PSReformat/.github/workflows/verify.yml@main

